# Generated by Django 4.0.2 on 2022-03-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0002_remove_customuser_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcar',
            old_name='mobile_no',
            new_name='RentPerDay',
        ),
        migrations.RenameField(
            model_name='bookcar',
            old_name='mail',
            new_name='SeatingCapacity',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='Payable_amout',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='addresss',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='joinig_date',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='plot_number',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='plot_size',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bookcar',
            name='VehicleModel',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookcar',
            name='VehicleNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookcar',
            name='date1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookcar',
            name='date2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookcar',
            name='ref_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
